   repos:
   - repo: https://github.com/charliermarsh/ruff-pre-commit
     rev: v0.1.6  # ou la version que vous souhaitez
     hooks:
       - id: ruff
   
   - repo: https://github.com/pre-commit/pre-commit-hooks
     rev: v4.4.0  # ou la version que vous souhaitez
     hooks:
       - id: check-merge-conflict
       - id: mixed-line-ending
   
   - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
     rev: v1.3.1  # ou la version que vous souhaitez
     hooks:
       - id: python-safety-dependencies-check