services:
  kotaemon_custom:
    build: .
    runtime: nvidia  # ← Cela fonctionnera une fois que Docker reconnaît le runtime
    container_name: kotaemon_custom_container
    ports:
      - "7860:7860"
    environment:
      - LLM_MODE=${LLM_MODE:-falcon}
      - EMBEDDING_MODE=${EMBEDDING_MODE:-local}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - HUGGINGFACE_HUB_TOKEN=${HUGGINGFACE_HUB_TOKEN:-}
      - FLOWSETTINGS_MODULE=sos_flowsettings
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    volumes:
      - ./ktem_app_data:/app/ktem_app_data:rw
      - ${DATA_ROOT:-./data}:/app/data:ro
      - ~/.cache/huggingface:/root/.cache/huggingface 
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
